services:
  postgres-db:
    restart: unless-stopped
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Fortaleza
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    restart: unless-stopped
    build: .
    container_name: api-fetcher-app
    depends_on:
      - postgres-db
    env_file:
      - .env
    environment:
      - DB_HOST=postgres-db
      - PYTHONUNBUFFERED=1
      - TZ=America/Fortaleza
    volumes:
      - ./data:/app/data
volumes:
  pgdata: